name: test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: build agent
        run: |
          cd agent
          gradle shadowJar

      - name: build spring
        run: |
          cd spring
          gradle bootJar

      - name: run server
        run: |
          java -javaagent:$GITHUB_WORKSPACE/agent/build/libs/java-agent-1.0-SNAPSHOT-all.jar=agentarg -jar $GITHUB_WORKSPACE/spring/build/libs/demo-0.0.1-SNAPSHOT.jar &

      - name: http request
        run: |
          sleep 10
          curl http://localhost:8080/
